export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Overview</h2>
        <p>
          Leaks (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) is an anonymous secret-sharing community. This policy explains what
          data we collect, how we use it, and the choices you have. By using Leaks you agree to the
          practices described below.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Information We Collect</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Account Information (Sign&nbsp;in&nbsp;with&nbsp;Apple):</strong>
            When you create an account we receive the anonymous identifier generated by Apple and, if you
            choose, the relay email address Apple provides. This identifier is used solely to authenticate
            you and is not visible to other users.
          </li>
          <li>
            <strong>Approximate Location&nbsp;Data:</strong> We collect your coarse location (for example, the
            centre of the city block you are on) when you create or browse secrets so that we can surface
            nearby content. The location displayed with a secret is further obfuscated so that no one can
            determine your exact or real-time whereabouts.
          </li>
          <li>
            <strong>Gender:</strong> You are asked to select a gender when signing up. This information is used
            only to personalise your experience (for example, filters and statistics) and is never shared
            publicly.
          </li>
          <li>
            <strong>Secret Content:</strong> The text of the secrets you post is stored on our servers so that
            it can be displayed to other users.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">What We Don&rsquo;t Collect</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your name, phone number, or other personal identifiers you do not explicitly provide</li>
          <li>Device identifiers for advertising purposes</li>
          <li>Cookies or cross-site tracking data</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">How We Use Your Information</h2>
        <p>We use the information we collect to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Authenticate your account and keep it secure</li>
          <li>Show you secrets that are relevant to your location</li>
          <li>Moderate content, fight spam, and enforce our community guidelines</li>
          <li>Understand and improve how Leaks is used</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Data Retention &amp; Deletion</h2>
        <p>
          Secrets remain on Leaks only for as long as you want them to. You can delete a secret at any time
          from within the app; once deleted it is permanently removed from our servers and is no longer
          visible to anyone.
        </p>
        <p>
          You can also delete your entire account — including all secrets, replies, votes, location history
          and profile information — with a single tap in the settings screen. When you confirm deletion, we
          immediately and irreversibly erase all associated data from our systems.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Data Protection</h2>
        <p>
          We employ industry-standard technical and organisational measures to safeguard the data we hold.
          Approximate location data is stored separately from precise coordinates and is never shared with
          other users or third parties.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Contact Us</h2>
        <p>
          If you have questions about this policy or wish to exercise your data rights, email us at
          <a className="underline ml-1" href="mailto:support@leaks.app">support@leaks.app</a>.
        </p>
      </section>
    </div>
  );
}
