export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <p className="text-sm opacity-70">Last updated: August 9, 2026</p>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Overview</h2>
        <p>
          Leaks (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) is an anonymous
          local community for sharing Leaks, asking questions, and answering
          people nearby. This policy explains what data we collect, how we use
          it, and the choices you have. By using Leaks you agree to the
          practices described below.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Information We Collect</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Account Information (Sign&nbsp;in&nbsp;with&nbsp;Apple):</strong>
            When you create an account we receive the anonymous identifier generated by Apple and, if you
            choose, the relay email address Apple provides. This identifier is used solely to authenticate
            you and is not visible to other users.
          </li>
          <li>
            <strong>Location&nbsp;Data:</strong> We use location when you create or browse local content so
            that we can surface relevant Leaks and questions. By default, the map shows a stable,
            obfuscated point rather than the exact coordinates selected for a post or question. An
            author can revisit their own selected location, while another authenticated user needs
            Premium to reveal it. A reveal does not provide live location tracking or the
            author&rsquo;s identity.
          </li>
          <li>
            <strong>Gender:</strong> You are asked to select a gender when signing up. This information is used
            to personalise your experience (for example, filters and statistics). If you select male or
            female, it may also appear as a hint to the author of a Leak or question you deliberately
            open, answer, like, or dislike. Other selections are omitted from Viewer Hints.
          </li>
          <li>
            <strong>Community Content:</strong> The text of the Leaks, questions, and answers you post is
            stored on our servers so that it can be displayed to other users. For Ask, the selected place
            label and an approximate map point are public; the exact target coordinates remain protected
            until an eligible viewer chooses to reveal them.
          </li>
        </ul>
      </section>

      <section id="location" className="space-y-4 scroll-mt-8">
        <h2 className="text-2xl font-semibold">Location and Viewer Hints</h2>
        <p>
          Leaks uses your approximate location to show local content and may create a Viewer Hint when you
          deliberately open, answer, like, or dislike someone else&rsquo;s Leak or accepted Ask question.
          When location is available for that interaction, Premium authors may see one stable obfuscated
          area with a radius of at least 500 metres, never your exact coordinates, name, email, or account
          ID. We may also show available device family and OS details, interaction time, whether you
          returned, the surface you opened from, your replies or reactions on that content, and male or
          female if selected in your profile. Other gender selections are omitted. Passive feed
          impressions do not create Viewer Hints.
        </p>
        <p>
          Viewer Hints and exact-location reveals are separate features. A Viewer Hint never grants an
          author access to a viewer&rsquo;s exact location. If Viewer Hints is disabled, new hint capture and
          Viewer Hint notifications stop, but this does not change how exact post or question locations
          are revealed.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">What We Don&rsquo;t Collect</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your name, phone number, or other personal identifiers you do not explicitly provide</li>
          <li>Device identifiers for advertising purposes</li>
          <li>Cookies or cross-site tracking data</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">How We Use Your Information</h2>
        <p>We use the information we collect to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Authenticate your account and keep it secure</li>
          <li>Show you secrets that are relevant to your location</li>
          <li>Moderate content, fight spam, and enforce our community guidelines</li>
          <li>Understand and improve how Leaks is used</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Data Retention &amp; Deletion</h2>
        <p>
          Secrets remain on Leaks only for as long as you want them to. You can delete a secret at any time
          from within the app; once deleted it is permanently removed from our servers and is no longer
          visible to anyone.
        </p>
        <p>
          You can also delete your entire account — including all secrets, replies, votes, location history
          and profile information — with a single tap in the settings screen. When you confirm deletion, we
          immediately and irreversibly erase all associated data from our systems.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Data Protection</h2>
        <p>
          We employ industry-standard technical and organisational measures to safeguard the data we hold.
          Viewer Hints store only an obfuscated approximate area and never expose a viewer&rsquo;s exact
          coordinates or account identifier.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Contact Us</h2>
        <p>
          If you have questions about this policy or wish to exercise your data rights, email us at
          <a className="underline ml-1" href="mailto:support@inkognito.app">support@inkognito.app</a>.
        </p>
      </section>
    </div>
  );
}
